import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://reservation.pc.gc.ca/');
  await page.getByRole('button', { name: 'I Consent' }).click();
  await page.locator('.mat-mdc-select-arrow > svg').first().click();
  await page.getByRole('option', { name: 'Banff', exact: true }).click();
  await page.getByRole('textbox', { name: 'Arrival' }).click();
  await page.getByRole('button', { name: 'February 2026, Select to' }).click();
  await page.getByRole('button', { name: 'July' }).click();
  await page.getByRole('button', { name: 'July 3,' }).click();
  await page.getByRole('button', { name: 'July 10,' }).click();
  await page.getByRole('spinbutton', { name: 'Party Size' }).click();
  await page.getByRole('spinbutton', { name: 'Party Size' }).fill('4');
  await page.locator('div:nth-child(2) > .mat-mdc-select-arrow > svg').click();
  await page.getByRole('option', { name: 'Medium Tent' }).click();
  await page.getByRole('button', { name: 'Search for availability' }).click();
  await page.getByRole('radio', { name: 'List view of results' }).click();
  await expect(page.locator('#ListView')).toContainText('No Available Sites');
  await expect(page.locator('#map-link-name-0')).toContainText('Site Tunnel Mountain - Village 1');
  await expect(page.getByLabel('Site Tunnel Mountain - Village')).toContainText('Available');
  await page.getByRole('button', { name: 'Site Tunnel Mountain -' }).click();
  await expect(page.getByRole('button', { name: 'Site A  Available' })).toBeVisible();
  await page.getByRole('button', { name: 'Site A  Available' }).click();
  await expect(page.getByRole('button', { name: 'Site A49  Available' })).toBeVisible();
  await page.getByRole('button', { name: 'Site A49  Available' }).click();
  await page.getByRole('button', { name: 'Reserve' }).click();
  await page.getByRole('button', { name: 'Acknowledge' }).click();
  await expect(page.getByRole('heading', { name: 'Please read and acknowledge' })).toBeVisible();
  await page.getByRole('checkbox', { name: 'All reservation details are' }).check();
  await page.getByRole('button', { name: 'Confirm reservation details' }).click();
  // await page.locator('.mapLinkArea-two-jack-main').click();
  // await page.locator('.mapLinkArea-loops-22-27').click();
  // await page.locator('[id="resourceSvg[-2147475364]"] > .icon-shape').click();
  // await page.getByRole('button', { name: 'Reserve' }).click();
  // await page.getByRole('button', { name: 'Acknowledge' }).click();
  // await page.getByRole('checkbox', { name: 'All reservation details are' }).check();
  // await page.getByRole('button', { name: 'Confirm reservation details' }).click();
  // await page.getByRole('button', { name: 'Proceed to checkout' }).click();
});